---
driver:
  name: docker

provisioner:
      name: chef_zero

platforms: 
  - name: centos-7 
    driver_config: 
      image: centos:7
      privileged: true # Needed by systemd to access cgroups
      run_command: /usr/sbin/init # Start systemd as root process
      use_sudo: false

suites:
  - name: default
    run_list:
        - recipe[td-agent::install]
    cookbook_path: "../../cookbooks"
    attributes:
