#
# This file is structured to be consumed by both humans and computers.
# It is a TOML document containing Markdown
#
[Preamble]
  title = "Maintainers"
  text = """

This file lists how this cookbook project is maintained. When making changes to the system, this file tells you who needs to review your patch - you need a review from an existing maintainer for the cookbook to provide a :+1: on your pull request. Additionally, you need to not receive a veto from a Lieutenant or the Project Lead.

Check out [How Cookbooks are Maintained](https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD) for details on the process and how to become a maintainer or the project lead.
"""

[Org]
  [Org.Components]
    [Org.Components.Core]
      title = "Project Maintainer"

      lieutenant = "wrightp"

      maintainers = [
        "jtimberman",
        "wrightp",
        "schisamo",
        "ncerny",
        "tduffield",
        "andrew-dufour",
        "mivok",
        "stephenlauck",
        "tas50",
      ]

[people]
  [people.jtimberman]
    name = "Joshua Timberman"
    github = "jtimberman"

  [people.wrightp]
    name = "Patrick Wright"
    github = "wrightp"

  [people.schisamo]
    name = "Seth Chisamore"
    github = "schisamo"

  [people.ncerny]
    name = "Nathan Cerny"
    github = "ncerny"

  [people.tduffield]
    name = "Tom Duffield"
    github = "tduffield"

  [people.andrew-dufour]
    name = "Andrew DuFour"
    github = "andrew-dufour"

  [people.mivok]
    name = "Mark Harrison"
    github = "mivok"

  [people.stephenlauck]
    name = "Stephen Lauck"
    github = "stephenlauck"

  [people.tas50]
    name = "Tim Smith"
    github = "tas50"
